version: "3.0"

services:
  
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    user: root
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - JENKINS_SLAVE_AGENT_PORT=8081
      - JAVA_OPTS="-Duser.timezone=Asia/Tokyo"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ./jenkins/key:/var/jenkins_key:ro
